name: Tim Williams Photography
favicon: null
layout_spectrum: 0.6702109277248383
typography_spectrum: 1
title: Tim Williams Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b9b9b9'
    - '#ffffff'
    - '#808080'
    - '#000000'
    - '#555555'
  brandStrength: 0.4375
  lightness: 0.28230420337058604
  saturation: 0.25
  rhythmicContrast: 0.1030960283242166
purpose: []
